Отладка добавляемых методов
nixel2007/decorator pull request #5
Opened 2022-09-05 23:01 UTC by Nivanchenko

Добавил возможность включать флаг отладки через метод или переменную окружения. 
При этом флаге сценарий загружается не из строки, а через временный файл. При такой схеме отладчик может "провалиться" в добавленный объект и его метод.

2022-09-06 07:05 UTC, nixel2007 requested changes
Это все не сильно пересекается с api v2 из пр Кирилла?)

2022-09-06 07:05 UTC, nixel2007 commented on src/Классы/КонструкторДекоратора.os
> +Функция Отладка() Экспорт
Кажется, нужен параметр. Чтобы это как сеттер работало. Значение параметра по умолчанию - истина

2022-09-06 07:05 UTC, nixel2007 commented on src/Классы/КонструкторДекоратора.os
> +
Добавь _ плз

2022-09-06 07:05 UTC, nixel2007 commented on src/Классы/КонструкторДекоратора.os
> -	Декоратор = ЗагрузитьСценарийИзСтроки(ТекстСценария);
Давай через fs. Чтобы был шанс их удалить после завершения работы приложения.
Хотелось бы вообще отдельный экземпляр менеджера временных файлов, но в рамках этой библиотеки пока не понимаю, куда его вставить, а деструкторов в оскрипте нет.

2022-09-06 07:40 UTC, Nivanchenko commented on src/Классы/КонструкторДекоратора.os
> +
Я не понял, куда добавить? =)

2022-09-06 07:42 UTC, Nivanchenko commented
> Это все не сильно пересекается с api v2 из пр Кирилла?)

Я не смотрел, проверю.

2022-09-06 08:42 UTC, nixel2007 commented on src/Классы/КонструкторДекоратора.os
> +
В переменную среды для отладки. Я видимо промахнулся с местом коммита

2022-09-06 09:12 UTC, Nivanchenko commented on src/Классы/КонструкторДекоратора.os
> +
"_OSCRIPTDECORATORDEBUG" так?

2022-09-06 09:50 UTC, nixel2007 commented on src/Классы/КонструкторДекоратора.os
> +
OSCRIPT_DECORATOR_DEBUG

2022-09-06 22:33 UTC, Nivanchenko commented
> Это все не сильно пересекается с api v2 из пр Кирилла?)

на сколько я могу судить, не пересекается.

2022-10-17 15:47 UTC, nixel2007 commented
@Nivanchenko добавь еще вот сюда, пожалуйста.

2022-10-17 15:47 UTC, nixel2007 commented
https://github.com/nixel2007/decorator/blob/master/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9F%D0%BE%D1%81%D1%82%D1%80%D0%BE%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%94%D0%B5%D0%BA%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%B0.os

2022-10-17 17:51 UTC, Nivanchenko commented
> @Nivanchenko добавь еще вот сюда, пожалуйста.

Готово ;)

2022-10-17 19:53 UTC, nixel2007 commented
доку?

2022-10-17 21:11 UTC, Nivanchenko commented
> доку?

Я за нее не подумал. Дописал для нового api.

2022-10-18 09:41 UTC, merged